chhoumann/quickadd

- docs/QuickAddAPI.md
In addition to reminding developers to await the method calls, wrapping the return type with a Promise helps communicate usage.
> Documents async method return types as Promises

- docs/Examples/Attachments/movies.js
This PR resolves a bug in `movies.js` where the `directorLink` is not properly linkified when a movie is directed by multiple people. 
Query: `The Matrix`
OMDb Response:
```
{
...
"Director": "Lana Wachowski, Lilly Wachowski",
...
}
```
Output: 
`{{VALUE.directorLink}}` renders `[[Lana Wachowski, Lilly Wachowski]]`
**Current Version Output**
**Output After PR**
> Linkify director list in movies.js

- src/gui/GenericInputPrompt/GenericInputPrompt.ts
Thanks for a very nice plugin!
I'm a Japanese user.
This plugin had a problem in the Capture input modal where the value being typed was being sent when a Japanese Kanji conversion was confirmed with the enter key. 
So I have fixed it.
reference: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing
> Prevent submit if press enter in composition session

- src/engine/TemplateChoiceEngine.ts
- src/gui/ChoiceBuilder/templateChoiceBuilder.ts
- src/types/choices/ITemplateChoice.ts
- src/types/choices/TemplateChoice.ts
Added an option to define the default behaviour if a file already exists at the creation path for a template.
If the behaviour is set then the user won't be prompted when the macro etc runs.
It's highly likely that the increment setting should be rolled into this but I wasn't entirely sure how to go about migrating settings etc
> Add option to set default behavior if file already exists for template

- src/gui/ChoiceBuilder/templateChoiceBuilder.ts
Followup from #391 I noted that my description field was poorly worded.
> fix: Fix description for file already exisiting setting

- esbuild.config.mjs
- package.json
- pnpm-lock.yaml
- src/MacrosManager.ts
- src/gui/ChoiceBuilder/macroChoiceBuilder.ts
- src/gui/choiceList/ChoiceView.svelte
- src/main.ts
- src/quickAddSettingsTab.ts
- src/settingsStore.ts
- src/styles.css
- tsconfig.json
- refactor: use settingsStore with Zustand
- refactor: use settingsStore in settings
- feat: button to access macro configuration from macro choice settings
- refactor: move macro creation to store
- refactor: unsubscribe from settings store
- fix: update references by explicitly returning new obj to update state
- fix: ensure choiceView has latest choices & macros
- feat: add macro from macro choice - no need to open macros manager
- refactor: fix type issue
- feat: macro choices with an associated macro (same name) will now delete the macro when deleting the choice
- fix: macros manager adding macros
> Macros QoL upgrade 18/03/23 - easier configure & adding macros from choices

- src/ai/OpenAIRequest.ts
- src/ai/preventCursorChange.ts
For some reason, when the request was made, the cursor would reset to the top of the file. I've added a mechanism to prevent this by simply restoring it to the pre-request state.
> fix: using AI assistant would place cursor at the top of the file - now stays in place

- src/formatters/captureChoiceFormatter.ts
This is a solution for issue #545 . As of Obsidian 1.4.0, the frontmatter position got moved from `frontmatter.position` to `frontmatterPosition`. See here: https://github.com/obsidianmd/obsidian-api/issues/122
As a result, the `getFrontmatterEndPosition` method in captureChoiceFormatter always returns `-1`, resulting in the note being added to the top of the file. This PR resolves that change in a backward compatible way by checking for both `frontmatter.position` and `frontmatterPosition`.
Unfortunately, I don't know how to test my changes. Any tips here would be appreciated.
> Resolving Issue #545: "Create line if not found" at Top inserted AFTER frontmatter

- src/main.ts
- src/quickAddSettingsTab.ts
Related to #575
This PR introduces a new quick add icon in the sidebar ribbon. The option can be configured in the settings page and defaults to hidden.
I wanted this feature for easier access to quick add on mobile.
> Add Sidebar Ribbon Icon

- src/formatters/helpers/getEndOfSection.test.ts
- src/formatters/helpers/getEndOfSection.ts
Fix #720.
In obsidian headings, there is at least one space after the hash sign (#), otherwise it should be treated as a tag.
> fix: heading pattern issue with leading tag

- src/logger/logManager.ts
Found minor issue
`logWarning` function didn't call current log level
and might result in expected behaviour
> correcting log level

- src/engine/CaptureChoiceEngine.ts
- src/engine/TemplateEngine.ts
- src/utilityObsidian.ts
- Fixes an issue where Templater commands weren't executing properly when using QuickAdd's Template and Capture choices
- Ensures consistent behavior across both choice types regardless of Templater settings
This issue was introduced as a side effect of fixing issue #533 in PR #783 (version 1.13.0), which addressed duplicate prompts in Capture choices. The fix modified how Templater commands are processed but inadvertently affected Templater command execution.
- Modified `CaptureChoiceEngine.ts` to always force Templater processing
- Updated `TemplateEngine.ts` to ensure consistent behavior across all choice types
- Improved `replaceTemplaterTemplatesInCreatedFile` in `utilityObsidian.ts` for better readability
- Fixes #787
- Maintains fix for #533
> fix: templater commands not executing correctly with QuickAdd

- docs/docs/Choices/TemplateChoice.md
- src/constants.ts
- src/engine/TemplateChoiceEngine.ts
- src/engine/TemplateEngine.ts
- src/engine/canvas-integration.test.ts
- src/formatters/formatter-default-values.test.ts
- src/formatters/formatter.test.ts
This PR adds support for canvas templates in QuickAdd, allowing users to create canvas files from canvas templates while preserving the correct file extension.
- **Added CANVAS_FILE_EXTENSION_REGEX constant** for  files
- **Modified TemplateEngine** to preserve canvas extensions when reading templates  
- **Updated TemplateChoiceEngine** to create files with correct extensions based on template type
- **Enhanced file validation** to allow both  and  files
- **Added template extension detection** and file path normalization methods
- **Updated file incrementation** to handle canvas extensions properly
- **Added comprehensive integration tests** for canvas functionality
- **Updated documentation** in TemplateChoice.md to document canvas template support
- ✅ All existing tests pass (353 …
> feat: add canvas template support

- src/gui/MacroGUIs/MacroBuilder.ts
Implements Solution 2 from the UX improvements analysis - a dual-action interface that provides both quick typing workflow and discoverable browse functionality for adding user scripts to macros.
- **Browse Button**: Opens modal file picker using existing InputSuggester
- **Dynamic Add Button**: Only appears when user types, hides when input is empty
- **Enhanced UX**: Clear placeholder text and improved descriptions  
- **Progressive Disclosure**: Clean initial state with actions appearing as needed
- **Consistent Behavior**: Add button hides after successful script addition
- **New Users**: Clear Browse button makes script selection discoverable
- **Power Users**: Preserved quick typing workflow with autocomplete
- **Visual Feedback**: Dynamic button visibility provides clear …
> feat: add Browse button for user script selection

- src/gui/suggesters/tagSuggester.ts
- src/gui/suggesters/utils.ts
- Fix double hashtag bug when selecting tag completions
- Replace stale cached position logic with dynamic calculation
- Add dispatchInput option to replaceRange for cleaner event control
- Prevent suggestion popup from reappearing after tag completion
Fixes #847
> fix: prevent double hashtag in tag completion

- src/formatters/completeFormatter.ts
- src/utils/DataviewIntegration.ts
- src/utils/InlineFieldParser.test.ts
- src/utils/InlineFieldParser.ts
Fixes #852: Resolves the regression where Unicode field names like `{{FIELD:经验归类}}` stopped working after v1.14.
v1.14 introduced two regressions that broke Unicode field names:
1. **InlineFieldParser regex too restrictive** - only accepted ASCII characters `[a-zA-Z0-9_\- ]+`
2. **No fallback mechanism** - when Dataview failed with non-ASCII field names, it didn't try manual parsing
- Updated regex from `[a-zA-Z0-9_\- ]+` to `[^:\n\r]+?` with `u` flag
- Now accepts any Unicode characters except colons and newlines
- Maintains backward compatibility with ASCII field names
- Modified `CompleteFormatter.suggestForField()` to fallback to manual parsing when Dataview returns no results
- Extracted manual parsing logic into reusable `collectValuesManually()` method
- Preserves existing behavior …
> Fix Unicode field name regression in {{FIELD:}} formatter

- docs/docs/Choices/TemplateChoice.md
- src/engine/TemplateChoiceEngine.ts
Implements automatic opening of existing files when users select 'Nothing' option in template choices, addressing the workflow issue described in #61.
- **TemplateChoiceEngine**: Enhanced to automatically open existing files when user chooses 'Nothing' option
- **Documentation**: Added new section explaining file exists behavior options
- **Code quality**: Refactored file name formatting to eliminate duplication
- When a file already exists and user selects 'Nothing' (don't modify), the file now automatically opens
- Respects all existing file opening preferences (new tab, direction, focus, mode)  
- Maintains backward compatibility with all other file exists options
- Eliminates need for users to configure multiple settings just to open existing files
Closes #61
> feat: auto-open existing files when using template choices

- src/engine/MacroChoiceEngine.ts
- src/gui/MacroGUIs/MacroBuilder.ts
- src/types/macros/EditorCommands/EditorCommandType.ts
- src/types/macros/EditorCommands/PasteWithFormatCommand.ts
Adds a new "Paste with format" macro command that preserves rich formatting from clipboard content.
- **New Command**: Added EditorCommandType.PasteWithFormat and PasteWithFormatCommand class
- **Rich Clipboard Support**: Uses navigator.clipboard.read() to access HTML content and converts to Markdown using Obsidian's htmlToMarkdown() function
- **Graceful Fallbacks**: Falls back to plain text when HTML is unavailable or on older Electron versions
- **UI Integration**: Added dropdown option in macro builder alongside existing editor commands
- **Cross-Platform**: Feature detection ensures compatibility with different Obsidian/Electron versions
1. **HTML Content**: When rich content (like formatted text with links) is copied, it reads the HTML and converts to proper Markdown
2. **Plain Text …
> feat: add paste with format command for rich clipboard content

- docs/docs/Choices/MacroChoice.md
- src/formatters/formatter.test.ts
- src/formatters/formatter.ts
Fixes issue #163 where empty string variables (`""`) were incorrectly triggering input prompts.
When users set variables to empty strings in their scripts (e.g., `QuickAdd.variables.myRating = ""`), QuickAdd would still prompt for input when encountering `{{VALUE:myRating}}` in templates. This was because the code used a truthiness check that treated empty strings as falsy values.
- **Added `hasConcreteVariable()` method** to properly distinguish between:
- Variables never set (should prompt)
- Variables explicitly set to empty string (should not prompt)  
- Variables set to undefined/null (should prompt)
- **Updated prompt logic** in both `replaceVariableInString` and `replaceFieldVarInString` methods
- **Added comprehensive test coverage** with 5 test cases covering all scenarios
- …
> Fix: Empty string variables no longer trigger prompts

- docs/docs/Choices/CaptureChoice.md
- docs/docs/Choices/TemplateChoice.md
- src/engine/CaptureChoiceEngine.ts
- src/engine/TemplateChoiceEngine.ts
- src/gui/ChoiceBuilder/captureChoiceBuilder.ts
- src/gui/ChoiceBuilder/templateChoiceBuilder.ts
- src/types/choices/ICaptureChoice.ts
- src/types/choices/ITemplateChoice.ts
- src/types/linkPlacement.test.ts
- src/types/linkPlacement.ts
- src/utilityObsidian.ts
Fixes #166
This PR adds configurable link placement options to both Capture and Template choices, solving the issue where Append link would unexpectedly replace selected text instead of appending after it.
- 4 Link Placement Options:
- Replace selection (default) - Maintains current behavior for backward compatibility
- After selection - Preserves selected text and appends link after it (Fixes the reported bug)
- End of line - Appends link to end of current line regardless of selection
- New line - Places link on a new line below cursor
- Added LinkPlacement type and AppendLinkOptions interface
- Enhanced ICaptureChoice and ITemplateChoice with backward-compatible union type
- Implemented insertLinkWithPlacement function with multi-cursor support
- Updated both choice engines to use the …
> feat: add configurable link placement options for capture and template choices

- src/engine/CaptureChoiceEngine.ts
- src/engine/captureAction.test.ts
- src/engine/captureAction.ts
- src/quickAddSettingsTab.ts
Implements feature request #180 to show visual confirmation when capture operations succeed.
- **Optional notifications**: Users can toggle capture notifications on/off in settings (defaults to enabled)
- **Contextual messages**: Different messages for different capture scenarios:
- `Captured to 'filename'` (append)
- `Captured to top of 'filename'` (prepend)
- `Captured to current line in 'filename'` (current line)
- `Captured to 'filename' under 'heading'` (insertAfter with heading context)
- `Created and captured to 'filename'` (new file creation)
- **Clear file delineation**: Filenames wrapped in single quotes for readability
- **4-second display duration**: Non-intrusive confirmation without blocking workflow
- Added `showCaptureNotification` boolean setting to QuickAddSettings …
> feat: Add capture confirmation notifications (#180)

- docs/docs/QuickAddAPI.md
- src/quickAddApi.ts
Adds an optional `allowCustomInput` parameter to the suggester API that allows users to enter custom text not present in the predefined suggestions list, similar to Obsidian's quick switcher behavior.
- Added `allowCustomInput` parameter (defaults to `false` for backward compatibility)
- When `true`, uses existing `InputSuggester` internally to allow custom input
- When `false`, uses existing `GenericSuggester` (current behavior)
- Updated API documentation with new parameter and usage examples
```javascript
// User can select from existing tags or type a new one
const existingTags = ["#project", "#personal", "#work"];
const selectedTag = await quickAddApi.suggester(
existingTags,
existingTags,
"Select existing tag or type new one",
true  // allowCustomInput = true
);
```
- ✅ Build passes …
> feat: add allowCustomInput parameter to suggester API

- docs/docs/AIAssistant.md
- src/ai/OpenAIRequest.ts
- src/ai/Provider.ts
- Add Google Gemini provider to default providers list
- Implement request routing to Gemini `generateContent` API
- Map supported params (temperature, top_p); omit unsupported ones that caused 400s
- Update docs to describe setup and compatibility
- Manual: Verified prompts work against `gemini-2.5-pro` with system prompts and temperature settings
- Confirmed no 400s for unsupported params
- Build + tests pass
Resolves #731
> feat(ai): add Gemini provider support

- docs/docs/Advanced/ObsidianUri.md
Add warning section explaining the fundamental limitation when using QuickAdd via URI with sync services. Files created on other devices won't be synced if Obsidian hasn't been opened, causing QuickAdd to create duplicates that overwrite synced versions.
Includes workarounds:
- Open Obsidian first and wait for sync
- Use device-specific naming conventions
- Capture to active file
- Include timestamps for uniqueness
References: #827
> docs: add sync limitation warning to Advanced URI documentation

- src/engine/CaptureChoiceEngine.ts
- src/engine/captureAction.test.ts
- src/engine/captureAction.ts
- src/gui/ChoiceBuilder/captureChoiceBuilder.ts
- src/types/choices/CaptureChoice.ts
- src/types/choices/ICaptureChoice.ts
- src/utilityObsidian.ts
Adds "New line above cursor" and "New line below cursor" capture location options to address the feature request in #525.
- **New capture actions**: Added `newLineAbove` and `newLineBelow` to the `CaptureAction` enum
- **UI enhancement**: Added conditional dropdown options when capturing to active file
- **Core functionality**: Implemented `insertOnNewLine()` utility with direction parameter  
- **Type safety**: Extended `ICaptureChoice` interface with `newLineCapture` property
- **Engine integration**: Updated `CaptureChoiceEngine` to handle new actions
- **Comprehensive testing**: Added tests for new functionality and edge cases
When "Capture to active file" is selected, users now see:
- "At cursor" (existing behavior - inserts exactly at cursor)
- **"New line above cursor"** (new - …
> feat: add new line capture options for cursor positioning (#525)

- src/engine/CaptureChoiceEngine.ts
Summary
- Symptom: In some capture flows that create a file then insert content, the capture line could be lost or moved after a final whole-file Templater pass.
Root Cause
- After creating a new file from a template, we ran Templater on the file and then read it with vault.cachedRead before embedding the capture. cachedRead can return stale content right after a write/render, making us insert into an outdated buffer. A subsequent whole-file Templater pass would then rewrite sections and effectively clobber or relocate the capture.
Fix
- New-file path now reads the file directly from disk with vault.read after the initial Templater run to guarantee fresh content before embedding the capture.
- We retain the final whole-file Templater pass for all captures. Because the capture is now …
> fix(capture): prevent captured content loss on newly created files

- src/formatters/capture-insert-after-linkcurrent.test.ts
- src/formatters/captureChoiceFormatter.ts
- src/formatters/completeFormatter.ts
Fixes #704
Summary
- Resolve {{linkcurrent}} and {{title}} in the 'Insert after' field so matching and creation use the resolved values instead of the literal tokens.
Details
- Apply link/title replacements to the Insert after target before searching.
- Apply the same replacements when 'Create if not found' inserts the target line.
- Keeps templater execution safeguards intact (no double execution).
Tests
- Added: src/formatters/capture-insert-after-linkcurrent.test.ts
- Verifies that {{linkcurrent}} resolves and content inserts after the actual link line.
- Verifies created line uses the resolved link when target is missing.
Notes
- Manual testing confirms the behavior.
- Broader suite has unrelated env issues under Bun; the new test runs in isolation.
> fix(insert-after): resolve {{linkcurrent}} and {{title}} in Insert after

- docs/docs/Advanced/onePageInputs.md
- docs/docs/QuickAddAPI.md
- src/gui/suggesters/SuggesterInputSuggest.ts
- src/gui/suggesters/suggest.ts
- src/preflight/OnePageInputModal.ts
- src/preflight/RequirementCollector.ts
- src/quickAddApi.ts
Closes #934
Implements multi-select functionality for the suggester field type in one-page inputs.
- Users can select multiple items from a suggester, separated by commas
- Suggestions stay open after each selection in multi-select mode
- Already-selected items are filtered from suggestions
- Supports both typing and selecting from dropdown
- ARIA accessibility attributes for screen reader support
```javascript
{
id: "tags",
type: "suggester",
options: ["#work", "#personal", "#urgent"],
suggesterConfig: {
multiSelect: true
}
}
```
```javascript
const values = await quickAddApi.requestInputs([
{
id: "tags",
label: "Select Tags",
type: "suggester",
options: ["#work", "#personal", "#project", "#urgent", "#review"],
suggesterConfig: {
multiSelect: true,
caseSensitive: false
}
}
]);
// Result: …
```
> feat: add multi-select support to suggester field type

- docs/docs/Choices/MacroChoice.md
- src/gui/MacroGUIs/MacroBuilder.ts
- src/gui/MacroGUIs/noScriptsFoundNotice.ts
This PR addresses user confusion reported in #895 by providing clear guidance when no JavaScript files are found in the vault.
- **Added informative notice**: When users click the Browse button and no .js files are found, they now see a helpful notice explaining:
- Scripts must be in the vault (not in .obsidian folder)
- Scripts cannot be in hidden folders (folders starting with a dot)
- Files must have a .js extension
- Includes a clickable link to the documentation
- **Updated documentation**: Clarified in MacroChoice.md that hidden folders (dot-prefixed like `.quickadd`) are not supported, with clear examples of valid vs invalid locations
- **Code organization**: Extracted notice logic to `noScriptsFoundNotice.ts` for better maintainability
Related to #895 (provides better user …
> feat: add helpful notice when no scripts found and clarify hidden folder restrictions
