chhoumann/quickadd

src/engine/TemplateChoiceEngine.ts

wait for path formatting without fileNameFormat

---

src/choiceExecutor.ts
src/constants.ts
src/gui/choiceList/ChoiceItemRightButtons.svelte
src/gui/choiceList/ChoiceList.svelte
src/gui/choiceList/ChoiceListItem.svelte
src/gui/choiceList/ChoiceView.svelte
src/gui/choiceList/MultiChoiceListItem.svelte
src/gui/choiceSuggester.ts
src/main.ts
src/types/choices/Choice.ts
src/types/choices/IChoice.ts
src/utility.ts

Choices can now become commands.

---

src/MacrosManager.ts
src/gui/MacroBuilder.ts
styles.css

- Macro Manager now mobile/table friendly & add scrolling effects
- Add ability to change macro names

Small UI/UX improvements

---

src/gui/GenericCheckboxPrompt/genericCheckboxPrompt.ts

Closes #63 
It was a simple issue of:
1. Ensuring the array you pass in is marked as `readonly` and then cloned so that users aren't caught by surprise when their values suddenly change. (Thanks Javascript, amazing design /s)
2. Setting the value of the toggle *first*, before defining the toggle handler. This way, toggling the initial values won't trigger an onChange.
Thanks

Fixes checkboxPrompt duplicates values

---

src/formatters/completeFormatter.ts
src/gui/GenericWideInputPrompt/GenericWideInputPrompt.ts
src/gui/GlobalSettings.ts
src/gui/InputPrompt.ts
src/gui/silentFileAndTagSuggester.ts
src/main.ts
src/quickAddApi.ts
src/quickAddSettingsTab.ts
styles.css

Add multi-line input prompt

---

src/gui/GenericYesNoPrompt/GenericYesNoPrompt.ts
src/gui/GenericYesNoPrompt/GenericYesNoPromptContent.svelte
styles.css

Should fix #165
Modal now automatically focuses the Yes button, so one can just click Enter to confirm.

Revamp YesNoPrompt to be selectable through keyboard.

---

src/engine/TemplateChoiceEngine.ts
src/engine/TemplateEngine.ts
src/formatters/completeFormatter.ts
src/gui/ChoiceBuilder/captureChoiceBuilder.ts
src/gui/ChoiceBuilder/macroChoiceBuilder.ts
src/gui/ChoiceBuilder/templateChoiceBuilder.ts
src/gui/GenericInputPrompt/GenericInputPrompt.ts
src/gui/GenericWideInputPrompt/GenericWideInputPrompt.ts
src/gui/GenericYesNoPrompt/GenericYesNoPrompt.ts
src/gui/MacroGUIs/MacroBuilder.ts
src/gui/MacroGUIs/UserScriptSettingsModal.ts
src/gui/MathModal.ts

Less restrictive folder handling & CSS classes

---

src/engine/MacroChoiceEngine.ts
src/utility.ts

Massive thanks to the contributors to [Templater](https://github.com/SilentVoid13/Templater). The implementation there really helped make this work.
This resolves #191, #79, #167, and #50.

Make user scripts work on mobile

---

src/engine/CaptureChoiceEngine.ts
src/formatters/captureChoiceFormatter.ts

Fix #225 and do some refactoring.

Fix bug where tasks added to file without frontmatter adds extra newline

---

README.md

- Improved the README by adding helpful information.
- Created with chatGPT, curated by Me.
The changes to the README were made with the help of an AI language model trained by OpenAI. The model was given the name and description of the plugin, as well as the current README and documentation for the plugin. Based on this information, the model generated a revised README file.
Do you know the app obsidian?
I will give you informations about an obsidian plugin and I want you to return a proper readme for its repository. 
Plugin name: QuickAdd;
Current readme: {{ paste from https://github.com/chhoumann/quickadd/blob/53e4f4cfbc1dfdbe83a6e4560d225487dadbb352/README.md }}
Current documentation home: {{ paste from https://quickadd.obsidian.guide/docs/ }}
Include the demo video in the readme; …

Update README with chatgpt help

---

docs/docs/Examples/Attachments/BookFinder.js
docs/docs/Examples/Macro_BookFinder.md

Christian as discussed last week on Discord. This is my first pull request ever.
For the code I've commented the obvious weaknesses:
- really should have a picker saying found X books with this name. Such a picker is made more complicated because some results from the Google Books api come back with undefined title (Bad API)
- Also I didn't take the time to elegantly concatenate all of the authors/categories of book with commas
I also wrote rudimentary docs, shamelessly stealing from your movie Script.

BookFinder added to QuickAdd as an example

---

src/engine/TemplateChoiceEngine.ts

Presently it always opens the file

Respect the openFile option when running a template and a file already exists

---

docs/docs/QuickAddAPI.md
src/gui/GenericInfoDialog/GenericInfoDialog.ts
src/quickAddApi.ts

Added a simple info dialog to be used within scripts instead of an ugly JS alert or similar. Existing dialogs didn't fill this purpose as they return a value or aren't really meant to be "informative" only.

Added Info Dialog as part of the API

---

src/constants.ts
src/formatters/completeFormatter.ts
src/formatters/formatter.ts
src/gui/GenericSuggester/genericSuggester.ts

FIELD searches all frontmatter for <variable> in the frontmatter of all markdown files.
Also implements partial autocomplete when pressing tab. Must have desired match under selection, otherwise it will just update to the current match (itself)

Added new format syntax {{FIELD:<variable>}}, and semi tab autocomplete

---

src/gui/choiceList/ChoiceListItem.svelte
src/gui/choiceList/MultiChoiceListItem.svelte
src/gui/suggesters/choiceSuggester.ts
src/styles.css

feat: render markdown & HTML in choice names

---

docs/docs/Choices/CaptureChoice.md
src/engine/CaptureChoiceEngine.ts
src/utilityObsidian.ts

- feat: Capture Anywhere: captures now support folder paths as the 'Capture To' target
- feat: Capture with Tag: put a tag in the capture path to capture to a file with that tag

Capture with Tag & Capture Anywhere

---

src/gui/GenericInputPrompt/GenericInputPrompt.ts
src/gui/GenericWideInputPrompt/GenericWideInputPrompt.ts
src/gui/choiceList/AddChoiceBox.svelte
src/gui/choiceList/ChoiceView.svelte

1. Updates choice creator
2. Updates modal button (gap)

Update button styling

---

src/gui/ChoiceBuilder/captureChoiceBuilder.ts

chore: fix missing space

---

src/formatters/completeFormatter.ts

Updates the field validator to check if the value is of type array and if so adds each member of the array to the suggested items.
Tested in my vault with the `tags` field.
```yaml
tags: 
- jrpg
- game
- foo
- bar
```
will now properly render each option

Update completeFormatter.ts to support arrays

---

src/styles.css

- Add max-width constraint to prevent excessive modal width
- Implement text wrapping for long content and code blocks
- Add proper overflow handling for code elements
- Ensure modal maintains readable layout with large content

fix: improve UpdateModal text overflow handling

---

src/formatters/captureChoiceFormatter.ts

Fixes issue #181 where "Insert After" incorrectly matches line prefixes instead of prioritizing exact matches.
When using Insert After with target "## Do", it would incorrectly insert after "## Done" if "## Done" appeared before "## Do" in the file, because the implementation used regex prefix matching.
Replaced regex-based matching with an efficient 3-tier priority system:
1. **Exact match** - `line.trimStart() === target` (highest priority)
2. **Regex-compatible match** - `target` + whitespace-only suffix (preserves old behavior)  
3. **Broader prefix fallback** - `line.startsWith(target)` (lowest priority)
- ✅ **Fixes the bug** - "## Do" no longer incorrectly matches "## Done"
- ✅ **Maintains backward compatibility** - all existing workflows continue working
- ✅ **Preserves indented …

Fix Insert After prefix matching bug

---

src/engine/CaptureChoiceEngine.ts
src/main.ts

Fixes issue where commands created from choices were not reflecting updated settings because the command callback captured the choice object directly in its closure.
Commands would always execute with the choice as it existed when the command was created, not the current state. Users had to toggle commands off/on for settings changes to take effect.
Modified `addCommandForChoice` in main.ts to:
- Capture only the choice ID instead of the entire choice object
- Look up the current choice dynamically at execution time using `getChoiceById()`
- Add proper error handling when a choice is not found
- Commands now execute with the latest choice settings automatically
- No need for users to toggle commands off/on when updating settings
- Proper error reporting if a choice is deleted after a …

Fix: Commands now use updated choice settings without requiring toggle

---

src/engine/CaptureChoiceEngine.ts
src/engine/MacroChoiceEngine.ts
src/engine/TemplateChoiceEngine.ts
src/engine/captureAction.test.ts
src/gui/ChoiceBuilder/captureChoiceBuilder.ts
src/gui/ChoiceBuilder/choiceBuilder.ts
src/gui/ChoiceBuilder/templateChoiceBuilder.ts
src/migrations/migrate.ts
src/migrations/migrateFileOpeningSettings.ts
src/quickAddSettingsTab.ts
src/types/choices/CaptureChoice.ts
src/types/choices/ICaptureChoice.ts
src/types/choices/ITemplateChoice.ts
src/types/choices/TemplateChoice.ts
src/types/fileOpening.ts
src/utilityObsidian.ts

This PR completely overhauls QuickAdd's file opening system, providing users with much more flexibility and control over where and how files are opened. The changes include 6 opening locations (instead of the previous 2), advanced view modes including Live Preview, and a modernized UI that only shows relevant options.
- **Reuse current tab** - Open in the currently active leaf
- **New tab** - Create a new tab in the active pane  
- **Split pane** - Split from the active pane (vertical/horizontal)
- **New window** - Open in a detached popout window
- **Left sidebar** - Open in the left sidebar
- **Right sidebar** - Open in the right sidebar
- **Source mode** - Raw Markdown editing
- **Reading view** - Preview/reading mode
- **Live Preview** - Live Preview editing mode (🎉 **Fixes #257**)
- …

feat: Enhanced file opening with flexible location and view mode options

---

docs/docs/Examples/Attachments/userScriptExample.js
docs/docs/UserScripts.md
docs/sidebars.js

- Created comprehensive documentation for user scripts explaining all configuration options
- Added complete example script demonstrating all available option types
- Integrated documentation into the Advanced section of the sidebar
- **New documentation page**: `docs/docs/UserScripts.md` - Complete guide covering:
- Basic script structure and module exports
- All option types (text, toggle, dropdown, format) with examples
- Settings configuration with descriptions and default values
- QuickAdd API usage examples
- Error handling and best practices
- Advanced patterns and debugging tips
- **Example script**: `docs/docs/Examples/Attachments/userScriptExample.js`
- Fully functional example demonstrating all option types
- Extensive inline comments
- Real-world use cases for each option type …

docs: Add comprehensive user scripts documentation
